### ISSUE TITLE
suggestion: use custom nonce on evm side to put all txs in one block

### ISSUE THREAD

**Issue by kuegi** [prasannavl/dfi-emissions-handler-bot#3]
currently the approve+addRewards+approve+addRewards with waiting for new blocks in between takes up a long time.
you could provide the nonce to the tx, and increment it each time. Then you don't need to wait for the new block but can send all 4 tx into the same block.

with bot execution schedule > 1 hour this is clearly no issue, but possible improvment

**Comment by prasannavl** [comment]
- https://github.com/prasannavl/dfi-emissions-handler-bot/pull/4 PR sets it up. Love the suggestion so, leaving it here - but still needs completion. Not sure if I'll be able to dig in anytime soon, given each sequence takes ~20 mins on good blocks, based on the last 10ish hours, which is OK since it's going to be on much larger intervals. 

- But leaving it here in case someone else is able to see this through to completion.

**Comment by prasannavl** [comment]
Resolved in https://github.com/prasannavl/dfi-emissions-handler-bot/pull/4
